# Generated by Django 3.2.8 on 2021-11-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
