version: '3'

services:
  django:
    build:
      context: './project'
      dockerfile: Dockerfile.prod
    container_name: 'chocotask_django'
    command: gunicorn config.wsgi:application -c config/gunicorn.conf.py --bind
      0.0.0.0:8000
    env_file:
      - ./.env.prod
    expose:
      - 8000
    volumes:
      - static_volume:/app/django/static
      - media_volume:/app/django/media
    depends_on:
      - db
  celery-worker:
    build:
      dockerfile: Dockerfile.celery
      context: ./project
    command: celery -A config worker -l info
    env_file:
      - ./.env.prod
    depends_on:
      - db
  celery-beat:
    build:
      dockerfile: Dockerfile.celery
      context: ./project
    command: celery -A config beat -l info
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  redis:
    image: redis:6-alpine
    expose:
      - 6379

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/app/django/static
      - media_volume:/app/django/media
    depends_on:
      - django

volumes:
  pg-data:
  static_volume:
  media_volume:
