# Generated by Django 3.2.8 on 2021-11-22 07:31

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', apps.accounts.models.CustomUserManager()),
            ],
        ),
    ]
